#!/bin/sh

FORMAT=$(echo " Poweroff\n Reboot\n󰋊 Hibernate\n󰒲 Sleep\n Lock session\n󰍃 Logout" | fuzzel --dmenu --anchor top-right --width 15 --lines 9 | awk '{print tolower($2)}')


case $FORMAT in
    poweroff)
        loginctl poweroff
        ;;
    reboot)
        loginctl reboot
        ;;
    lock)
        hyprlock
        ;;
    sleep)
        loginctl suspend
        ;;
    logout)
        hyprctl dispatch exit
        ;;
    hibernate)
        loginctl hibernate
        ;;
esac
